### ISSUE TITLE
Funktion a und b main und Achsenbeschriftungen

### ISSUE THREAD

**Issue by hannahbartmn** [hannahbartmn/WisA#10]
Bei den beiden Funktionen fänd ich es sinnvoll, wenn man die die Achsenbeschriftungen und Überschriften schon im Voraus festlegt, da man bei den vier Plots in a zum Beispiel ja dann ja sonst alle Plots die gleiche Überschrift bekommen. Was meint ihr?

**Comment by MaikeBr0** [comment]
Meinst du das im Sinne davon, dass man das einen festen Satz gibt, wo dann nur die Variable ergänzt wird in den Titel. Also zB "Hist von [Variable]", mit einen Befehl, wie 'main = paste("Hist von ", main)',  dass es sich ganz automatisiert, dass sich die Achsenbeschriftungen in der Funktion selbst anhand der gewählt Variable wählt, oder anders? Wobei ich beim zweiten nicht genau wüsst, wie man genau mit zB 'if' schaut, welche Variable man genau ansieht.

**Comment by JuNaPh** [comment]
Ich hatte eine ähnliche Idee wie Maike, nämlich, dass man für die einzelnen Plots "Histogramm für"[Variable] oder "Boxplot für" [Variable] als Überschrift nehmen könnte. Das geht ganz gut mit deparse(substitute()), das gibt den Namen der Variable aus. Also könnte man zB für den Boxplot schreiben: main = c("Boxplot für", deparse(substitute(x)) ). Wenn ich für x meine Variable "Alter" einsetze, wird die Überschrift zu "Boxplot für Alter". Auch bei den Achsenbeschriftungen würde ich damit arbeiten und je nach Plot xlab oder ylab gleich deparse(substitute(x)) setzen. So muss man am Anfang nicht extra die Überschrift eingeben und jeder Plot hat eine eigene Überschrift, die die Art des Plots und den Namen der Variable beinhaltet.
Kleine Anmerkung noch: bei dem vorletzten "if" in Funktion (a) steht noch "plot", ich glaube, das sollte ein "boxplot" sein :)

**Comment by hannahbartmn** [comment]
Das ist eine gute Idee, danke! Das versuche ich mal mit substitute. 
Und das mit dem boxplot habe ich auch noch geändert, danke :)
