### ISSUE TITLE
Verständnisfrage zur Funktion c

### ISSUE THREAD

**Issue by hannahbartmn** [hannahbartmn/WisA#11]
Zu Funktion c habe ich jetzt eine Funktion geschrieben, die Kreuztabellen (einmal mit relativen Häufigkeiten und einmal mit absoluten Häufigkeiten) ausgibt. Ich bin mir jetz aber echt ein bisschen unsicher, ob das schon alles gewesen ist. Meint ihr, das passt zu der Beschreibung der Funktion: "Eine Funktion, die geeignete deskriptive bivariate Statistiken für den Zusammenhang zwischen zwei kategorialen Variablen berechnet ausgibt"?

**Comment by hannahbartmn** [comment]
Ich habe noch die Spearman Korrelation hinzugefügt mit der Abfrage, ob beide Daten ordinal sind, weil es sonst ja keinen Sinn machen würde

**Comment by MaikeBr0** [comment]
Tut mir leid für die späte Antwort, aber mir ist auch nichts eingefallen, was da noch mit rein könnte. Mit berechnet ist denke ich auch nicht unbedingt Visualisieren gemeint, sonst hätte man höchstens noch etwas grafisches machen können, wie einen ggplot mit geom_bar. Aber da konnte man bei meinen Versuchen bis jetzt nicht die beiden Interessens Variablen gleichzeitig machen, bzw generell eine Interessensvariable für die Farbe wählen, weil sieben zu viel war (zumindestens ging es bei 2 und 4). Alternativ könnte man als Visualisierung von zwei Variablen mit ggplot und geom_jitter arbeiten und dabei die Variablen richtig als x und y setzen, statt eins mit Farbe zu visualisieren. 
Aber wie gesagt wären dies nur visuelle Ansätze.

**Comment by hannahbartmn** [comment]
alles klar, danke trotzdem :) ich glaube so wie die Funktion jetzt ist, würden wir sie lassen
