### ISSUE TITLE
Auswertung - für Alina und Hannah

### ISSUE THREAD

**Issue by hannahbartmn** [hannahbartmn/WisA#13]
Huhu Alina, ich habe mit deiner Vorarbeit vom Einlesen schonmal angefangen den Datensatz schonmal ein bisschen zu analysieren. Ich habe eine kleine Überscicht gemacht, welche Funktionen vielleicht für welches Merkmal mehr sinnvoll sind als andere, das hat mir als Orientierung sehr geholfen. Ich habe mich jetzt erstmal besonders auf Interesse an Programmieren, Interesse an Mathe und Mathe-Lk orientiert.

**Comment by Alina958** [comment]
Hey :) 
Ich hab mir jetzt mal die Verteilung vom Alter und den Studiengängen angeschaut. 
Außerdem habe ich mich mit dem Zusammenhang von Interesse an Mathe/Informatik und 
dem Studienfach der Personen beschäftigt. Meiner Meinung nach ist es nicht 
sinnvoll, dass wir noch das Merkmal ID in die Auswertungen mit aufnehmen, da wir 
ja keine Rückschlüsse auf bestimmte Personen ziehen möchten. Oder was meinst du?

**Comment by hannahbartmn** [comment]
Ja, da stimme ich zu. Ich fange hier mal eine kleine Zusammenfassung unserer Ergebnisse an: 

- Durchschnittsalter: 25 Jahre, Std.abweichung von 2.35
- Studienfächer: Statistik ist am häufigsten vertreten (36%), dann Data Science (28%), dann Informatik (22%) und Mathe ist am wenigsten vertreten (14%)
- Es besteht ein Zusammenhang zwischen dem Interesse an Mathe/Programmieren mit dem Studiengang: In den Studiengängen Mathe, Statistik und Data Science herrscht ein mittelmäßiges bis hohes interesse an Mathe, während beim Studiengang Informatik nur ein mittelmäßiges Interesse an Mathe besteht. Bei den Studiengängen Informatik und Data Science liegt ein großes Interesse am Programmieren vor.
- Diejenigen, die Mathe-Lk hatten scheinen ein stärkeres Interesse an Mathe zu haben als diejenigen ohne Mathe-Lk.
- Der Mathe-Lk scheint aber keinen/bzw. nur einen geringen Einfluss auf das Interesse an Programmieren zu haben. 
- Es besteht keine Korrelation zwischen dem Interesse an Mathe und dem Interesse an Programmieren.

Das hätte ich zusammengefasst über unsere Auswertung gesagt. Fehlt dir noch was? Wenn nicht, könnten wir ein neues issue machen, wo wir die Ergebnisse reinkopieren, in dem wir noch zusammen die abschließende Diskussion halten können. :)

**Comment by Alina958** [comment]
Die Zusammenfassung finde ich so gut und enthält meiner Meinung nach auch alle wichtigen Punkte. Den Issue kann ich auch gleich für unsere Gruppe erstellen. Wenn das für dich in Ordnung ist würde ich die Zusammenfassung auch nochmal in dem Branch ergänzen.

**Comment by hannahbartmn** [comment]
Das klingt gut :)
