### ISSUE TITLE
Funktion f - Visualisierung 4 Variablen

### ISSUE THREAD

**Issue by MaikeBr0** [hannahbartmn/WisA#7]
Für drei Variablen habe ich bereits eine Visualisierung gefunden, jedoch fehlt für die fertige Funktion noch eine, welche Mathe_Int, Prog_Int, Studienfach und Mathe_LK, also alle vier gleichzeitig anzeigt. Habt ihr Ideen dafür?

**Comment by Alina958** [comment]
Mit einem gruppierten Barplot könnte man alle vier Variablen gleichzeitig visualisieren. Auf dieser Seite findest du ein Code Beispiel wie man so einen Plot in R erstellt : https://statisticsglobe.com/draw-grouped-barplot-in-r

**Comment by MaikeBr0** [comment]
Hey, danke für den Link. Habe mir die Seite mal angeschaut. Bei mir gab es Probleme mit der y-Achse bei den Barplots, bin darüber aber weiter gekommen und habe neue Ideen für eine andere Version bekommen.
