### ISSUE TITLE
Funktion a- nicht alle Grafiken in einem Plot 

### ISSUE THREAD

**Issue by Alina958** [hannahbartmn/WisA#8]
Diese Funktion zeigt jetzt vier Grafiken in einem Plot an, ohne den Befehl par(mfrow = c(2,2)) hat 
die Funktion bei mir nicht funktioniert. Vielleicht könnte man die Funktion so umschreiben, dass sie die 
Plots auch einzeln anzeigen kann. Habt ihr eine Idee wie das gehen könnte?

**Comment by hannahbartmn** [comment]
Man könnte einen zusätzlichen Parameter einfügen, dem man eine Nummer von 1 bis 4 übergeben könnte. Mit einer if Abfrage könnte man dann spezifisch nur eine der vier Grafiken abrufen. 
Dieser Parameter könnte per default auf 0 gesetzt sein, sodass wenn man keine Nummer spezifiziert, er alle vier Plots mit der 2 x 2 Darstellung anzeigt. 
Ich könnte mal versuchen, das zu implementieren

**Comment by hannahbartmn** [comment]
Okay, das klappt. Der default ist auf 0, dann werden alle Plots in einem angezeigt, wenn man 1, 2, 3 oder 4 bei dem parameter plot angibt, kommt nur die entsprechende Abbildung.
