### ISSUE TITLE
Funktion b - Bisher nur zwei Visualisierungen 

### ISSUE THREAD

**Issue by Alina958** [hannahbartmn/WisA#9]
Die Funktion macht bisher nur zwei Visualisierungen. Die Vierfeldertafel muss man noch auf unser Datenbeispiel umschreiben. Als Idee könnte man bei weiteren Visualisierungen mit Rängen arbeiten, aber das hab ich bisher nicht richtig hingekommen. Meiner Meinung nach wäre es ganz schön, wenn wir für b eine Funktion schreiben, die drei oder vier Visualisierungen zeigen kann.

**Comment by hannahbartmn** [comment]
Ich glaube, wenn man das auch mit dem deparse(substitute(x)) macht, wie Julia und Maike das schon bei der Funktion a vorgeschlagen haben, übernimmt der das direkt mit den Namen und man muss nicht ganz viele if Abfragen oder so schreiben, um jede einzelne Kombination abzudecken. Ich versuche das mal umzusetzen :)

**Comment by hannahbartmn** [comment]
Ich habe eine Abfrage eingefügt, ob dieses kategorielle Merkmal ordinal ist. Weil wenn es niminal ist, dann macht eigentlich keine andere Visualisierung außer einem Balkendiagramm und einer Häufigkeitstabelle Sinn. Zumindest ist mir jetz tim Moment nichts anderes eingefallen. Wenn das Merkmal ordinal ist, dann macht noch ein Boxplot Sinn, deswegen habe ich den dann noch hinzugefügt. Die Funktion ist jetzt halt so aufgebaut, dass die Anwendenen wissen, ob das Merkmal ordinal ist, aber da ja eh letztendlich nur wir damit arbeiten, dachte ich mir, kann man das so stehen lassen :D zumindest ist mir keine Abfrage eingefallen, mit der man herausfinden kann, ob das Merkmal des eingegebenen Datenvektors ordinal oder nominal ist

**Comment by MaikeBr0** [comment]
Mir sind leider auch keine weiteren Visualisierungen o.ä. eingefallen. Aber müssen es zwangsweise Visualisierungen sein, oder könnte man auch andere bivariate Statistiken nutzen? Also sowas wie summary, cor usw halt für kategoriale Variablen

**Comment by hannahbartmn** [comment]
ich habe die b jetzt so verstanden, dass das für univariate Merkmale ist und das bivariate in Funktion c abgedeckt ist. Ich würde die Funktion einfach so lassen, wie sie jetzt ist :)
